Implement Contract Verification
modularcloud/explorer pull request #100
Opened 2023-06-12 21:48 UTC by pynchmeister

## Description 

Contract verification now exists at ```/contract```. Allows users to provide a contract address, source code, and metadata files in order to verify smart contracts using the Sourcify API.

## Screenshot

<img width="817" alt="Screenshot 2023-06-12 at 5 45 44 PM" src="https://github.com/modularcloud/explorer/assets/33232379/271ab899-3ceb-4f88-8cdb-c4db6d6030d2">

## Future Work

May include displaying the contract verification on the same page as applicable contract addresses.

2023-06-13 20:29 UTC, lzrscg requested changes

2023-06-13 20:29 UTC, lzrscg commented on apps/web/pages/api/contract-verification/prisma/contract-verification.ts
> +  const { contractAddress, chainId, files, uploadedFilesFolderUrl } = req.body;
how do we determine the chainId?

2023-06-13 20:29 UTC, lzrscg commented on apps/web/pages/api/contract-verification/prisma/lib/prisma.ts
> +import { PrismaClient } from '@prisma/client';
I see a lot of files are inside the `/api` directory. I believe this should only be reserved for routes. Can you move the non-API routes elsewhere?

2023-06-13 20:29 UTC, lzrscg commented on apps/web/tsconfig.json
>    "extends": "tsconfig/nextjs.json",
can you try extending this base definition? I believe there is a package for this in the monorepo:
`/packages/tsconfig`

2023-06-13 20:29 UTC, lzrscg commented on babel.config.js
> +module.exports = {
can you explain why this was necessary? I don't have an issue with it, just want to understand

2023-06-13 20:29 UTC, lzrscg commented on package.json
> +    "@babel/preset-typescript": "^7.21.5",
can you install all dependencies in the `web` package.json instead

`npm i mypackage --workspace=web`

2023-06-13 20:29 UTC, lzrscg commented on packages/tailwind-config/tailwind.config.js
> +  mode: "jit",
also curious why this was necessary?

2023-06-14 02:55 UTC, mhstom commented on apps/web/pages/api/file-upload/generateurl.ts
> +export default async function generateS3Url(
who is using this?

2023-06-14 14:37 UTC, Aswanth-c commented on packages/tailwind-config/tailwind.config.js
> +  mode: "jit",
It's better to enable tailwind jit 

The build time was slow and enabling jit helped in reducing the build time

You can read more here 

https://v2.tailwindcss.com/docs/just-in-time-mode

2023-06-14 23:39 UTC, pynchmeister commented on babel.config.js
> +module.exports = {
seems unnecessary, so it has been removed

2023-06-15 01:47 UTC, pynchmeister commented on apps/web/tsconfig.json
>    "extends": "tsconfig/nextjs.json",
sure thing

2023-06-19 04:14 UTC, mhstom commented on apps/web/ui/contract-verify/verifyAndUpload.tsx
> +        const uploadImage = await axios.put(getImageUploadUrl.data.url, file, {
could we compress the file before uploading?

2023-06-19 04:15 UTC, mhstom reviewed
For the upload to s3 logic, could we compress the file before uploading?

2023-06-20 22:42 UTC, mhstom commented on apps/verify/contract-verify/pages/verifyAndUpload.tsx
> +              await uploadFile(zipFile);
if I am reading the code correctly, we are uploading files to s3 BEFORE sending the file to sourcify. Is that intentional? Any reason to store the files before they are verified?

2023-06-20 22:48 UTC, lzrscg requested changes
This looks really good!

- Please ensure minimal changes occur outside of the `verify` directory.
- Why did you call it `verify/contract-verify` instead of just `verify` or `contract-verify`? It's not a problem, but just curious?

2023-06-20 22:48 UTC, lzrscg commented on apps/web/jest.config.js
is this change still necessary?

2023-06-20 22:48 UTC, lzrscg commented on apps/web/package.json
> +    "postinstall": "prisma generate",
is this change still necessary?

2023-06-20 22:48 UTC, lzrscg commented on apps/web/pages/_app.tsx
> +import '../styles/globals.css';
is this change still necessary?

2023-06-20 22:48 UTC, lzrscg commented on apps/web/tsconfig.json
> +  "compilerOptions": {
is this change still necessary?

2023-06-20 22:48 UTC, lzrscg commented on packages/@modularcloud/design-system/components/contract-verify/index.tsx
> +export function ContractVerify() {
no need to change this, but we are deprecating `@modularcloud/design-system`

this can just go the verify project folder

2023-06-20 22:48 UTC, lzrscg commented on packages/tailwind-config/tailwind.config.js
> +  mode: "jit",
I thought this was enabled by default?

2023-06-20 22:48 UTC, lzrscg commented on apps/verify/contract-verify/prisma/lib/prisma.ts
> +  prisma = new PrismaClient();
does this need an environment variable?

2023-06-20 22:50 UTC, mhstom commented on apps/verify/contract-verify/pages/api/contract-verification/contract-verification.ts
> +              response.data.result[0].status == "perfect" ? "FULL" : "PARTIAL",
what do FULL and PARTIAL mean?

2023-06-20 22:53 UTC, pynchmeister commented on apps/web/package.json
> +    "postinstall": "prisma generate",
No, this is unnecessary as it was moved to the ```verify``` project

2023-06-20 23:01 UTC, pynchmeister commented
> * Why did you call it `verify/contract-verify` instead of just `verify` or `contract-verify`? It's not a problem, but just curious?

I moved the folder manually and it was called ```verify/contract-verify``` originally. But it is much cleaner as ```verify``` so I've switched it to that.

2023-06-20 23:02 UTC, mhstom commented on apps/verify/contract-verify/pages/verifyAndUpload.tsx
> +              await uploadFile(zipFile);
if I am reading the code correctly, we are uploading files to s3 BEFORE sending the file to sourcify for verification. Is that intentional? Any reason to store the files before they are verified?

2023-06-20 23:02 UTC, mhstom commented on apps/verify/contract-verify/pages/api/contract-verification/contract-verification.ts
> +              response.data.result[0].status == "perfect" ? "FULL" : "PARTIAL",
what do FULL and PARTIAL mean? When would the result be PARTIAL?

2023-06-21 00:19 UTC, Aswanth-c commented on apps/web/package.json
we can get rid of the changes here
as we wont be using it

2023-06-21 02:58 UTC, merged