Verify documentation
modularcloud/explorer pull request #103
Opened 2023-06-22 01:31 UTC by pynchmeister

## Description

* Added documentation for contract verification at ```/explorer/apps/verify/README.md```.

* Added smart contract verification functionality to ```@modularcloud/sdk```

2023-06-22 01:50 UTC, lzrscg requested changes

2023-06-22 01:50 UTC, lzrscg commented on packages/@modularcloud/sdk/index.ts
> +        return VerificationResponseSchema.parse(json.result);
This result should not be a `VerificationResponse` (`{ verified: boolean }`). It should contain a the text of the source code from the files returned by the API.

2023-06-22 01:50 UTC, lzrscg commented on packages/@modularcloud/sdk/index.ts
> +          `${baseUrl}/api/contract-verification/fetch-verified?contractaddress=${address}`
this base URL is different from the other URLs in this file, our API is located at the URL:
[contract-verification.vercel.app](https://contract-verification.vercel.app/)

Go ahead and hardcode this in

2023-06-22 01:50 UTC, lzrscg commented on apps/verify/README.md
> +* 200 OK: The operation was successful. The response body will contain the verification data for the contract. If no contract is found with the provided address, { "isVerified": false } will be retur
what is the schema if `readfiles` is `true`?

2023-06-22 01:56 UTC, mhstom commented on apps/verify/README.md
> +**/api/contract-verification/**
maybe I am missing something but shouldn't this be `api/contract-verification/verify-contract` ?

2023-06-22 01:56 UTC, mhstom commented on apps/verify/README.md
> +This endpoint is used to verify a smart contract. The verification is done by making an API call to a Sourcify service (or a localhost if no Sourcify URL is provided in the environment variables). De
the description looks more like https://github.com/modularcloud/explorer/blob/main/apps/verify/pages/verifyAndUpload.tsx to me.

the actual api doesn't seem to be doing that much? https://github.com/modularcloud/explorer/blob/main/apps/verify/pages/api/contract-verification/verify-contract.ts

2023-06-22 01:56 UTC, mhstom commented on apps/verify/README.md
> +## Prisma
where is the command to generate the db and tables?

2023-06-22 02:01 UTC, mhstom commented on apps/verify/README.md
> +**/api/fetch-verified**
and shouldn't this be /api/contract-verification/fetch-verified based on the repo route here? https://github.com/modularcloud/explorer/blob/main/apps/verify/pages/api/contract-verification/fetch-verified.ts

2023-06-22 02:06 UTC, pynchmeister commented on apps/verify/README.md
> +**/api/contract-verification/**
No, you are correct--I made a mistake. Fixed.

2023-06-22 02:15 UTC, pynchmeister commented on apps/verify/README.md
> +This endpoint is used to verify a smart contract. The verification is done by making an API call to a Sourcify service (or a localhost if no Sourcify URL is provided in the environment variables). De
Ok, I've edited the description. Let me know if your point still stands.

2023-06-22 02:18 UTC, pynchmeister commented on apps/verify/README.md
> +## Prisma
added

2023-06-22 02:19 UTC, pynchmeister commented on apps/verify/README.md
> +**/api/fetch-verified**
This is correct, just changed it.

2023-06-22 02:22 UTC, pynchmeister commented on apps/verify/README.md
> +* 200 OK: The operation was successful. The response body will contain the verification data for the contract. If no contract is found with the provided address, { "isVerified": false } will be retur
```{
  "id": "string",
  "createdAt": "datetime",
  "updatedAt": "datetime",
  "verificationStatus": "string",
  "contractAddress": "string",
  "chainID": "string",
  "isVerified": "boolean",
  "uploadedUrl": "string",
  "files": "Object"
}
```

Added this to the docs

2023-06-22 02:24 UTC, mhstom commented on apps/verify/README.md
> +This API endpoint is designed to handle the verification of smart contracts. The verification is done by making an API call to a Sourcify service (or a localhost if no Sourcify URL is provided in the
**After** the verification is done by making an API call to a Sourcify service, (or a localhost if no Sourcify URL is provided in the environment variables), this api create a record in the database that stores the verification status of the contract.

2023-06-22 02:24 UTC, pynchmeister commented on packages/@modularcloud/sdk/index.ts
> +        return VerificationResponseSchema.parse(json.result);
Noted.

2023-06-22 02:29 UTC, pynchmeister commented on apps/verify/README.md
> +This API endpoint is designed to handle the verification of smart contracts. The verification is done by making an API call to a Sourcify service (or a localhost if no Sourcify URL is provided in the
I've replaced my description with yours.

2023-06-22 19:13 UTC, Aswanth-c commented on apps/verify/README.md
> +* 200 OK: The operation was successful. The response body will contain the verification data for the contract. If no contract is found with the provided address, { "isVerified": false } will be retur
Schema with data for more convenience 
`{
    "id": 14,
    "contractAddress": "0x90cd9b9f69d1db3f66dd209784c90b92b0157b40",
    "chainID": "91002",
    "isVerified": true,
    "createdAt": "2023-06-21T21:11:39.028Z",
    "updatedAt": "2023-06-21T21:11:39.028Z",
    "verificationStatus": "FULL",
    "uploadedUrl": "https://verified-contracts.s3.us-west-2.amazonaws.com/0x90cd9b9f69d1db3f66dd209784c90b92b0157b40/0x90cd9b9f69d1db3f66dd209784c90b92b0157b40_sourcefiles.zip",
    "files": {
        "Caldera.sol": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.17;\n\ncontract HelloWorld {\n\n    string saySomething;\n\n    constructor() {\n        saySomething = \"Hello World!\";\n    }\n\n    function speak() public view returns(string memory) {\n        return saySomething;\n    }\n}",
        "metadata.json": "{\n\t\"compiler\": {\n\t\t\"version\": \"0.8.18+commit.87f61d96\"\n\t},\n\t\"language\": \"Solidity\",\n\t\"output\": {\n\t\t\"abi\": [\n\t\t\t{\n\t\t\t\t\"inputs\": [],\n\t\t\t\t\"stateMutability\": \"nonpayable\",\n\t\t\t\t\"type\": \"constructor\"\n\t\t\t},\n\t\t\t{\n\t\t\t\t\"inputs\": [],\n\t\t\t\t\"name\": \"speak\",\n\t\t\t\t\"outputs\": [\n\t\t\t\t\t{\n\t\t\t\t\t\t\"internalType\": \"string\",\n\t\t\t\t\t\t\"name\": \"\",\n\t\t\t\t\t\t\"type\": \"string\"\n\t\t\t\t\t}\n\t\t\t\t],\n\t\t\t\t\"stateMutability\": \"view\",\n\t\t\t\t\"type\": \"function\"\n\t\t\t}\n\t\t],\n\t\t\"devdoc\": {\n\t\t\t\"kind\": \"dev\",\n\t\t\t\"methods\": {},\n\t\t\t\"version\": 1\n\t\t},\n\t\t\"userdoc\": {\n\t\t\t\"kind\": \"user\",\n\t\t\t\"methods\": {},\n\t\t\t\"version\": 1\n\t\t}\n\t},\n\t\"settings\": {\n\t\t\"compilationTarget\": {\n\t\t\t\"Caldera.sol\": \"HelloWorld\"\n\t\t},\n\t\t\"evmVersion\": \"paris\",\n\t\t\"libraries\": {},\n\t\t\"metadata\": {\n\t\t\t\"bytecodeHash\": \"ipfs\"\n\t\t},\n\t\t\"optimizer\": {\n\t\t\t\"enabled\": false,\n\t\t\t\"runs\": 200\n\t\t},\n\t\t\"remappings\": []\n\t},\n\t\"sources\": {\n\t\t\"Caldera.sol\": {\n\t\t\t\"keccak256\": \"0x8f54065335b9a9019f30a20b9e2cb182aeec5d823ded5c67e71c22f42422b892\",\n\t\t\t\"license\": \"MIT\",\n\t\t\t\"urls\": [\n\t\t\t\t\"bzz-raw://21b5e98caff1f4831c23977aa77c9063fe735d843cb722ebda428715f586dcf2\",\n\t\t\t\t\"dweb:/ipfs/QmSk3zRdU2fxWEaw7em9PJ6LJuupxWgM1snGwqbNZgBB2W\"\n\t\t\t]\n\t\t}\n\t},\n\t\"version\": 1\n}"
    }
}`

2023-06-22 20:15 UTC, lzrscg commented on packages/@modularcloud/sdk/schemas.ts
> +  sourceCode: z.string(),
why is this response just a single string. Isn't it possible to have multiple source files? what about file names?

2023-06-23 00:19 UTC, lzrscg requested changes

2023-06-23 00:19 UTC, lzrscg commented on packages/@modularcloud/sdk/index.ts
> +        return VerificationResponseSchema.parse(json.result);
I think this is the wrong schema. Can you test this as well?

2023-06-23 18:58 UTC, merged