0825 merge contract verification to branch0818 nautilus mainnet stats page
modularcloud/explorer pull request #151
Opened 2023-08-25 20:40 UTC by mhstom

Planning to merge https://github.com/modularcloud/explorer/commit/a320a36ccf9570bc31fa844e15ec9056c1c4d311 to branch `0818NautilusMainnetStatsPage` as currently the naut-mainnet is using that branch.

Creating this pr to test before merging

2023-08-31 00:15 UTC, lzrscg commented
what was the status of this @mhstom? did we need to merge or close this?

2023-09-01 03:14 UTC, mhstom commented
At the time of this pr, naut mainnet was on branch 0818NautilusMainnetStatsPage. I was planning to merge https://github.com/modularcloud/explorer/commit/a320a36ccf9570bc31fa844e15ec9056c1c4d311 to branch 0818NautilusMainnetStatsPage to fix the naut mainnet contract verification. Before that I created this PR to test. However seems like naut mainnet contract verification feature worked without merging this change so I didn't merge.

But I feel like to have better code, we should still merge it?

2023-09-01 03:48 UTC, lzrscg requested changes

2023-09-01 03:48 UTC, lzrscg commented on apps/web/lib/networks.ts
>    if (whitelabel.env === "nautilus") {
interesting, this is super confusing but actually `nautilus` whitelabel is for triton.nautscan.com (to be deprecated soon)

`nautscan` is for nautscan.com

2023-09-01 03:48 UTC, lzrscg commented on apps/verify/ui/verifyAndUpload.tsx
> +  const [chainId, setChainId] = useState<string>("22222");
I wonder if this is still needed with upcoming/recent changes

2023-09-01 03:48 UTC, lzrscg commented on apps/verify/ui/chainSelectableComponent.tsx
> -            name: "Nautilus Proteus Testnet",
these changes make sense, but I also wonder if this is still needed given @Aswanth-c 's work

2023-09-01 03:48 UTC, lzrscg commented on apps/verify/pages/api/contract-verification/fetch-verified.ts
> +      chainID = "22222";
this too

2023-09-01 03:48 UTC, lzrscg commented on apps/docs/src/pages/verification.mdx
> +3. Ensure **Nautilus Mainnet** is selected in the dropdown.
should't we update the docs more comprehensively so that it can explain that proteus and mainnet are both options? @rubyanddiamond will do this once the new UI is done

2023-09-08 06:12 UTC, Aswanth-c commented
> At the time of this pr, naut mainnet was on branch 0818NautilusMainnetStatsPage. I was planning to merge [a320a36](https://github.com/modularcloud/explorer/commit/a320a36ccf9570bc31fa844e15ec9056c1c4d311) to branch 0818NautilusMainnetStatsPage to fix the naut mainnet contract verification. Before that I created this PR to test. However seems like naut mainnet contract verification feature worked without merging this change so I didn't merge.
> 
> But I feel like to have better code, we should still merge it?

Naut main is now on the main branch right? if so 
I think it's better to close this PR as these changes are already present in the main.

2023-09-08 16:59 UTC, mhstom commented
> Naut main is now on the main branch right? if so
I think it's better to close this PR as these changes are already present in the main.

no it's not. It's still on 0818NautilusMainnetStatsPage branch

2023-11-26 02:11 UTC, closed without merging