Remove references to Proteus
modularcloud/explorer pull request #152
Opened 2023-08-28 17:40 UTC by pynchmeister

## Resolves #144

2023-08-31 00:15 UTC, lzrscg requested changes

2023-08-31 00:15 UTC, lzrscg commented on apps/docs/src/pages/verification.mdx
> +Modular Cloud enables [NautScan](https://nautscan.com) users to verify contracts on the [Nautilus Mainnet network](https://docs.nautchain.xyz/nautilus-mainnet), powered by [Sourcify](https://sourcify
Maybe this should say that it is available for both the proteus and mainnet networks?

what do you think @rubyanddiamond

2023-08-31 00:21 UTC, pynchmeister commented on apps/docs/src/pages/verification.mdx
> +Modular Cloud enables [NautScan](https://nautscan.com) users to verify contracts on the [Nautilus Mainnet network](https://docs.nautchain.xyz/nautilus-mainnet), powered by [Sourcify](https://sourcify
Sounds good to me. Also this PR removes references to Proteus when it should remove Triton references instead. Fixing now.

2023-09-01 03:04 UTC, lzrscg commented
not exactly what's needed, let's wait for @rubyanddiamond to fill out more info 🙏

2023-09-01 03:04 UTC, closed without merging