Fix mainnet implementation
modularcloud/explorer pull request #153
Opened 2023-08-28 18:07 UTC by pynchmeister

2023-08-31 00:13 UTC, lzrscg requested changes

2023-08-31 00:13 UTC, lzrscg commented on apps/web/lib/networks.ts
> -  if (whitelabel.env === "nautilus") {
sorry if it's not clear, but `nautscan` is the expected environment variable for main net

FYI @Aswanth-c in case you didn't know that either

2023-08-31 00:19 UTC, pynchmeister commented on apps/web/lib/networks.ts
> -  if (whitelabel.env === "nautilus") {
Noted, thanks

2023-09-01 03:03 UTC, lzrscg commented
I think this is solving a problem that was resolved in another PR. and we will update the docs later. going to close this for now 🙏

2023-09-01 03:03 UTC, closed without merging