♻️ replace old toaster with sonner toaster
modularcloud/explorer pull request #404
Opened 2024-02-22 22:55 UTC by Fredkiss3

## Before

<img width="430" alt="image" src="https://github.com/modularcloud/explorer/assets/38298743/f5e72a40-5884-4ea5-8b09-67b1b8efa4c8">

## After

<img width="400" alt="image" src="https://github.com/modularcloud/explorer/assets/38298743/1b6e9a56-252e-4f59-90bf-1ba9e7663813">

<img width="388" alt="image" src="https://github.com/modularcloud/explorer/assets/38298743/a7be0e19-f54a-429f-b42a-62146ff36893">

2024-02-22 23:31 UTC, lzrscg requested changes

2024-02-22 23:31 UTC, lzrscg commented on apps/web/ui/copyable-value/index.tsx
> +                    label: "ok",
small request: "Ok" instead of "ok"

2024-02-22 23:31 UTC, lzrscg commented on apps/web/ui/entity/overview/blob.tsx
> +          label: "ok",
given that there is the same logic repeated in many places, do you think we could make some sort of more generalized component/function to handle copying

2024-02-23 02:55 UTC, Fredkiss3 commented on apps/web/ui/entity/overview/blob.tsx
> +          label: "ok",
Hm... I will look up if we can do that on the `Toaster` component itself, because if we make a wrapper it will be too thin.

2024-02-23 03:02 UTC, lzrscg commented on apps/web/ui/entity/overview/blob.tsx
> +          label: "ok",
oh you are right

2024-02-23 03:02 UTC, Fredkiss3 commented on apps/web/ui/copyable-value/index.tsx
> +                    label: "ok",
What do you think of just adding a `close` button to every toast ?

<img width="399" alt="image" src="https://github.com/modularcloud/explorer/assets/38298743/5e719423-0738-4cb1-bee7-776fa68c723c">

<img width="399" alt="image" src="https://github.com/modularcloud/explorer/assets/38298743/e8b35d3a-1199-4653-a671-3189f3c7cea4">

2024-02-23 03:04 UTC, Fredkiss3 commented on apps/web/ui/copyable-value/index.tsx
> +                    label: "ok",
I also pushed that version and can roll back if necessary.

2024-02-23 03:08 UTC, merged