Implemented Layout of the explorer
modularcloud/explorer pull request #61
Opened 2023-05-02 07:46 UTC by bolajahmad

### Updates

This is a layout of the explorer board built into the `apps/web` workspace. This is a fully UI based implementation with very little UI logic.

Imlemented charts and table layout

2023-05-02 22:43 UTC, lzrscg requested changes
looks great! I pointed out some things I think you probably already knew! but just wanted to be sure they were on your radar. I'm hoping that we can follow the exact Figma designs as closely as possible.

2023-05-02 22:43 UTC, lzrscg commented on apps/web/app/page.tsx
> +                    <td className="pb-2">
I think this should probably be `py` instead of `pb` because the top also needs some spacing

2023-05-02 22:43 UTC, lzrscg commented on apps/web/app/page.tsx
> +                  <tr key={block.id} className="border-b-2">
should be `border-b` because the width in Figma is 1px.
<img width="219" alt="Screenshot 2023-05-02 at 3 27 16 PM" src="https://user-images.githubusercontent.com/84213303/235799013-b42c55aa-68fa-42d6-8454-cdbabd3fb467.png">

Also `border-color-[rgba(8,6,21,0.06)]`

2023-05-02 22:43 UTC, lzrscg commented on apps/web/app/page.tsx
> +        <div className="border-2 rounded-xl py-8 bg-white max-w-5xl mx-auto divide-x-2 mt-8 flex items-center justify-center gap-6">
Also here the border is 1px and please apply the box shadow
```
border: 1px solid rgba(42, 43, 46, 0.1);
box-shadow: 0px 3px 6px rgba(42, 43, 46, 0.07), 0px 1px 2px rgba(42, 43, 46, 0.04);
```

2023-05-02 22:43 UTC, lzrscg commented on apps/web/app/page.tsx
> +        <div className="flex items-center justify-between mx-auto gap-16 max-w-5xl">
I think the items should not be at the center, but actually top justified: `items-start`

2023-05-02 22:43 UTC, lzrscg commented on apps/web/app/page.tsx
> +              <span className="font-bold text-night">ZBC Price</span>
`whitespace-nowrap`

2023-05-02 22:43 UTC, lzrscg commented on apps/web/app/page.tsx
> +                      <button className="border-2 rounded-3xl py-2 px-3">
these don't need to be buttons. also, check out the existing component called `Badge`. It might be helpful

`apps/web/app/[network]/[type]/(standard)/[query]/[[...viewPath]]/(components)/badge.tsx`

2023-05-03 09:04 UTC, bolajahmad commented on apps/web/app/page.tsx
> +                    <td className="pb-2">
That is true, I will fix this!

2023-05-03 09:07 UTC, bolajahmad commented on apps/web/app/page.tsx
> +                  <tr key={block.id} className="border-b-2">
Thank you for providing the actual color, this is the `night-600`.

2023-05-03 09:41 UTC, bolajahmad commented on apps/web/app/page.tsx
> +        <div className="flex items-center justify-between mx-auto gap-16 max-w-5xl">
I don't understand this. The flex-items are flexed along with the chart. Justifying to the top would only make the summary start at the top with the chart, here is what it looks like.

<img width="1139" alt="Screenshot 2023-05-03 at 10 41 10" src="https://user-images.githubusercontent.com/56865496/235882775-dbd49091-7b71-4fd4-8fd4-c76522e5be44.png">

2023-05-03 10:40 UTC, bolajahmad commented on apps/web/app/page.tsx
> +                      <button className="border-2 rounded-3xl py-2 px-3">
the Badge is certainly useful, I have replaced the button with a badge.

2023-05-03 10:40 UTC, bolajahmad commented on apps/web/app/page.tsx
> +              <span className="font-bold text-night">ZBC Price</span>
This had already been fixed with the white-space and I moved it into a its own component

2023-05-03 10:41 UTC, bolajahmad commented on apps/web/app/page.tsx
> +        <div className="border-2 rounded-xl py-8 bg-white max-w-5xl mx-auto divide-x-2 mt-8 flex items-center justify-center gap-6">
Also resolved already 💯

2023-05-03 10:43 UTC, bolajahmad commented
I have updated the PR with the changes you noted, do let me know if you notice any other inconsistencies @lzrscg

2023-05-04 11:04 UTC, bolajahmad commented on apps/web/app/page.tsx
> +        <div className="flex items-center justify-between mx-auto gap-16 max-w-5xl">
![Screenshot 2023-05-04 at 12 01 05](https://user-images.githubusercontent.com/56865496/236185698-57894b9e-61be-4e59-8f6f-5709e182c14d.png)

I am not sure I understand the change required here, the market summary info look well-aligned, and very close to the Figma. Maybe I'm just not quick enough to figure it out, could you describe the problem here better?

2023-05-04 11:38 UTC, bolajahmad commented
I updated this PR with the gradient color styling also. That pretty much sums up the designing.

I will open a new PR and subsequent updates will be on the new branch. 

cc @lzrscg

2023-05-09 01:18 UTC, closed without merging