Changed Home page title to explorer by modular cloud
modularcloud/explorer pull request #87
Opened 2023-05-10 10:50 UTC by Aswanth-c

Fixed the mentioned Issue  https://github.com/modularcloud/explorer/issues/62

2023-05-11 00:55 UTC, lzrscg requested changes
This won't work, unfortunately. What needs to happen is we need to edit the whitelabel object (from `getWhitelabel()`) to include a custom whitelabel field for each explorer.

Thanks for getting this started :)

2023-05-11 00:56 UTC, lzrscg commented
for example, celestiascan.com should say "CelestiaScan by Modular Cloud"

2023-05-11 05:20 UTC, Aswanth-c commented
> This won't work, unfortunately. What needs to happen is we need to edit the whitelabel object (from `getWhitelabel()`) to include a custom whitelabel field for each explorer.
> 
> Thanks for getting this started :)

Hey Lz, sorry for the misunderstanding.

I have fixed the issue by
creating a property  Inside the whiteLableObject variable and naming it "title". 
In most of the cases, I  combined the name array and added those values to the title property. 
except In world and default env where the names  are ["modular" "cloud"], I changed it to explorer

2023-05-11 14:42 UTC, lzrscg commented
thanks @Aswanth-c this is great! I was thinking maybe the full title could go in the metadata. So for instance,

"Explorer by Modular Cloud"
"CelestiaScan by Modular Cloud"
"Something else entirely"

Could all be the title.

Perhaps something like this could be added to the whitelabel config:
```
{
   "metadata": {
      "title": "Explorer by Modular Cloud",
      "description": "A modular block explorer built by Modular Cloud",
   }
}
```

2023-05-11 16:02 UTC, Aswanth-c commented
> erhaps something like this could be added to the whitelabel config:

Done!

2023-05-11 18:22 UTC, lzrscg requested changes
LGTM after the capitalization fix :D

2023-05-11 18:22 UTC, lzrscg commented on apps/web/lib/utils.ts
> +export type metaData = {
sorry to be a nitpicker 🥺👉👈 but can you rename this "Metadata"

2023-05-12 04:38 UTC, Aswanth-c commented on apps/web/lib/utils.ts
> +export type metaData = {
Haha nice catch
Fixed!

2023-05-27 00:11 UTC, lzrscg commented
i fixed this in a previous update already, thanks for putting this together though!

2023-05-27 00:11 UTC, closed without merging