added dynamic searchbar Glow by using onFocus and onBlur
modularcloud/explorer pull request #89
Opened 2023-05-11 06:12 UTC by Aswanth-c

Searchbar glows on focus

2023-05-11 06:14 UTC, Aswanth-c commented
fixed the mentioned Issue https://github.com/modularcloud/explorer/issues/64
> Added Searchbar glows on focus

2023-05-11 14:45 UTC, lzrscg requested changes
can we do this with pure CSS? I think it makes sense to use `hover:` and `focus:`
https://tailwindcss.com/docs/hover-focus-and-other-states#pseudo-classes

what do you think?

2023-05-11 16:44 UTC, Aswanth-c commented
> can we do this with pure CSS? I think it makes sense to use `hover:` and `focus:` https://tailwindcss.com/docs/hover-focus-and-other-states#pseudo-classes
> 
> what do you think?

Yep, I tried that, but it doesn't work because the input element is only 1/3, and we want the glow on the whole div element. 

eg, if I try to use  focus in the input area 
![image](https://github.com/modularcloud/explorer/assets/57211637/9a3221c1-0355-4d49-8327-30469ec51842)

Another thing I want to mention is I created a wrapper div and styled it because it's better to have a wrapper div if we are using gradient color for  search barglow

2023-05-11 18:19 UTC, lzrscg commented on apps/web/app/[network]/[type]/(standard)/[query]/[[...viewPath]]/(components)/search.tsx
> +        <div className={searchBarGlow ? "p-[1px] rounded-lg bg-[#9DAAE2]" : ""}>
oh good point, then just add the pseudo class here and user `hover:`

`focus:` won't work but its not necessary

2023-05-12 04:30 UTC, Aswanth-c commented on apps/web/app/[network]/[type]/(standard)/[query]/[[...viewPath]]/(components)/search.tsx
> +        <div className={searchBarGlow ? "p-[1px] rounded-lg bg-[#9DAAE2]" : ""}>
Did you mean adding the glow on hover also? I have added that on the latest commit

2023-05-27 00:22 UTC, lzrscg commented
this needs to be a super simple CSS only change

when the search bar (not text input box) is hovered, it glows (using the CSS pseudoclass)

2023-08-31 00:21 UTC, lzrscg commented
closing for now

2023-08-31 00:21 UTC, closed without merging