Stats to client
modularcloud/explorer pull request #91
Opened 2023-05-12 14:17 UTC by bolajahmad

2023-05-14 16:05 UTC, bolajahmad commented
@lzrscg , I updated the api routes earlier yesterday. I'm sorry the updates came late, but it works just fine now

2023-05-16 01:55 UTC, lzrscg requested changes

2023-05-16 06:47 UTC, bolajahmad commented on apps/web/lib/utils.ts
> +        subText: "The future is now",
Yes, this is removed now. The subText should be undefined

2023-05-27 00:23 UTC, lzrscg commented
this ended up becoming unnecessary due to some other changes we pushed. thanks for putting this together though!

2023-05-27 00:23 UTC, closed without merging